[build]
  publish = "."
  command = "" # Use this only if you have a build step, otherwise leave it empty.

[[redirects]]
  from = "/"
  to = "/login/"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/dashboard.html"
  status = 200

[[redirects]]
  from = "/registration"
  to = "/registration/registration.html"
  status = 200
