[build]
  publish = "."
  command = "" # If you have a build step, specify it here; otherwise, leave it empty.

[[redirects]]
  from = "/"
  to = "/login/"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/dashboard.html"
  status = 200

[[redirects]]
  from = "/registration"
  to = "/registration/registration.html"
  status = 200
